# Generated by Django 5.2 on 2025-04-08 16:04

import django.db.models.deletion
import parking_space.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField(default=False)),
                ('history', models.JSONField(default=parking_space.models.ParkingSpace.create_list, null=True)),
                ('occupied_by', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle')),
            ],
        ),
    ]
